# Default values for sealDemo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

## The trick here is sealedSecretName must match the name of the secret you created in step 1
sealedSecretName: "foo-secret"
sealedSecrets:
  supersecretfile_1: 'AgAs567ol75pTyhbIohz/4jihRZT3hENlVYacriFIaRxVK4OirLAnwQY1D22rcqmc7BhCMjNMA8e6INfEUAe9d4hvktEzQcKTpRXxnLUvpaTh1NQIWTwlOEdArRO7Y7yIyXTeo3fPkJZEhIF5FH/XPED//L2H/qU0vtSQ28LWX00kSQwP0g/RciwWrLa9577QVL0R+EVgqrXiHNtVi6KUXXav/rMXt8tnzfM8u13Pa8aK4zpnWghWiKJqLnoZwfeu/dn/0zhIq3J1goVf0LtoZ96afRRYFZbuey64ONHxDiz4tHgObv06V5QzdJ3q4Albd28orC5a54ZS8E+n475MoUN+S5vtP8LB55A8a0YpfF8uxSaN+D2Auc1Od5aWVAE7c9eZQZkqn8GLtsx2ws+d+YXOCV4GR4ifkXmt8xQ/3UrAiQwbMn7IAzkvWbOmqfSnPWLO4vb4nmzRY3iOiQCZ+tklqW4MdOByTRO1vdDnOlJeQcCHuWlknqIRjIy2gIEQmqUsxONPe/D/5r5DZqogeXGElAurxaqUSZPVvf0LHlBShpxGJJZeN4Rz1PBgzU9IK2+qbIwwm68hUd1NUXSJJuRUm2dE2WMO5B7JM1WSaDxLfD9oTFRLhts9yHrAuBHXQ/BdKr0a2qqqWUsEEUnwmgeXUC6E3Zui4qYgrvsyhOZJ+0fICgBlrUKYQ6ywflt3n9IuXCNNjpcK4aeTsM4XZVEBillTUaOv1rbAsC+TDRPjQg0kpZTimLd2AdTumb3j0BkLkNdhfYudV/6yrwdMaCMZRvgCM1gWTFlBM+kFuNHJaxABbpvgQ=='
  supersecretfile_2: 'AgAEKYWsm9oLOVKSZZb4lwfmgqhRmy5FRgb5Ds1kJXCOp5iKFWL9KzF01nBMbPLGR+KQvkjit3ebzHzhLFpvjocjVsWqMpp7RBo4kTZ4+hkmcGzSwNohX1WOca0hACZKt1vzY3g9kbA25HJ08u7LzoqXNInXLEmZv7sMfFvxyahAOaNgToHLyZoOrbjV0o0uARE2l/IeSqsbrQYLJ5Ab8IIvCrHeKdDpngpGX6ud3nTVPGj9G290p1LHMc/G2jVLIyNzPAqXtH03CMKurJF2rXlKSyFP2S6RXqeTQu5fqBlCY7kNsQm0pD9ktrsbzchP7FnKjaNtEgN66Tuayap77BBIfhgh9omRa8IO1sEvD5FwRJbkishUrMMddJvJyH+YZ9bzXFx3KUHod1zGmlByakWuuQKko2H0BTZKRYfD31ptNBfWRO4B+xPOvy8TwYcXkW4IzbrXQ7QDZEpm2YZsaIkdtwNOtMffTYj+AHlDp90iXAiAygUMEa6Ka0dRcMS8Da0jqUOq86a+BQzZK4DFkKZxUr6BmfOYHDXCAs3RJSBKHjHTGT+wJTwBZlxzG+noFsb95sVIq4jTApGUnJLufnfXux5Z8dSYxHJU1ieGU6VvX0ooYxWpACQWML0YCVrkPFezMyayfQYQQeCjB2hK/xTopx5ZknHzUE+a0i3X5JVzWAWXuNLisv6CmbNlX4L+ezfThokBktsZuNv2h70QB76U'

replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart version.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
