apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.sealedSecretName }}
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    {{- range $key, $val := .Values.sealedSecrets }}
    {{ $key }}: {{ $val }}
    {{- end }}
